name: Supertest

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 5' # Run at 12:00 PM UTC on Fridays

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run Supertest
      run: npm test
